name: DataSci_env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - anyio=4.9.0=pyh29332c3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311he736701_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.4=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli-python=1.1.0=py311hda3d55a_2
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.4.26=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.7.14=py311haa95532_0
  - cffi=1.17.1=py311he736701_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - cpython=3.11.13=py311hd8ed1ab_0
  - debugpy=1.8.14=py311hda3d55a_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py311h827c3e9_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=9.3.0=pyh6be1c34_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - json5=0.12.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py311h1ea47a8_1
  - jsonschema=4.24.0=pyhd8ed1ab_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.24.0=hd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhe01879c_2
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.16.0=pyhe01879c_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.13=py311haa95532_0
  - krb5=1.21.3=hdf4eb48_0
  - libexpat=2.7.0=he0c23c2_0
  - libffi=3.4.6=h537db12_1
  - liblzma=5.8.1=h2466b09_1
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.50.0=h67fdade_0
  - libzlib=1.3.1=h2466b09_2
  - markupsafe=3.0.2=py311h5082efb_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.3=pyh29332c3_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py311haa95532_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=7.4.3=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - openssl=3.5.0=ha4e3fda_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1.1=pyh8b19718_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.8=pyhe01879c_0
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py311he736701_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.13=h3f84c4b_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.11=7_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=307=py311hda3d55a_3
  - pywinpty=2.0.15=py311hda3d55a_0
  - pyyaml=6.0.2=py311h5082efb_2
  - pyzmq=26.4.0=py311h484c95c_0
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.25.1=py311hc4022dc_0
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.7=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.13.3=py311haa95532_1
  - terminado=0.18.1=pyh5737063_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h2c6b04d_2
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.5.1=py311he736701_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250516=pyhd8ed1ab_0
  - typing-extensions=4.14.0=h32cad80_0
  - typing_extensions=4.14.0=pyhe01879c_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - ucrt=10.0.22621.0=h57928b3_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.4.0=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_26
  - vc14_runtime=14.42.34438=hfd919c2_26
  - vs2015_runtime=14.42.34438=h7142326_26
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.5=ha9f60a1_7
  - zipp=3.22.0=pyhd8ed1ab_0
  - zstandard=0.23.0=py311he736701_2
  - pip:
      - absl-py==2.3.1
      - altair==5.5.0
      - astunparse==1.6.3
      - blinker==1.9.0
      - cachetools==6.1.0
      - click==8.2.1
      - comtypes==1.4.12
      - contourpy==1.3.2
      - cycler==0.12.1
      - deepxde==1.15.0
      - et-xmlfile==2.0.0
      - filelock==3.20.0
      - flatbuffers==25.2.10
      - fonttools==4.58.1
      - formulaic==1.2.1
      - fsspec==2025.12.0
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-pasta==0.2.0
      - grpcio==1.73.1
      - h5py==3.14.0
      - interface-meta==1.3.0
      - ipywidgets==8.1.7
      - joblib==1.5.1
      - jupyterlab-widgets==3.0.15
      - keras==3.10.0
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - linearmodels==7.0
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mypy-extensions==1.1.0
      - namex==0.1.0
      - narwhals==1.41.1
      - networkx==3.6.1
      - numpy==2.1.3
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optree==0.16.0
      - pandas==2.3.0
      - patsy==1.0.2
      - pillow==11.2.1
      - plotly==6.1.2
      - protobuf==5.29.5
      - pyaml==25.7.0
      - pyarrow==20.0.0
      - pydeck==0.9.1
      - pyhdfe==0.2.0
      - pyparsing==3.2.3
      - pyperclip==1.11.0
      - pywinauto==0.6.9
      - pyxlsb==1.0.10
      - rich==14.0.0
      - scikit-learn==1.7.0
      - scikit-optimize==0.10.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - smmap==5.0.2
      - statsmodels==0.14.5
      - streamlit==1.46.1
      - tenacity==9.1.2
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - torch==2.9.1+cu126
      - torchvision==0.24.1+cu126
      - tzdata==2025.2
      - watchdog==6.0.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - xlwings==0.33.15
prefix: C:\Users\nasca\anaconda3\envs\DataSci_env
